# Dockerfile

# pull the official docker image
FROM python:3.11.1

# set env variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# create dir and assign the folder as the main
RUN mkdir ML
WORKDIR /ML

# copy project, config, env
COPY ./ML .
COPY ./.env .
COPY ./config.py .

# copy and install requirments
COPY ./docker/ML/requirements.txt .
RUN pip install -r requirements.txt
