{
 "title": "Docker Containers",
 "description": "Containers metric",
 "tags": [ "docker" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Container Work Status",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_last_seen{name=~\"redis|cadvisor|grafana|ml|frontend|nodeexporter|alertmanager|postgres|prometheus|api\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Docker and Server ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Load",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[1m])) / count(node_cpu_seconds_total{mode=\"user\"}) * 100"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 7, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "node_time_seconds - node_boot_time_seconds"
      }
     ]
    },
    {
     "title": "Memory Load",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 11, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
      }
     ]
    },
    {
     "title": "Used Memory",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 15, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{image!=\"\"})"
      }
     ]
    },
    {
     "title": "Used Storage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "sum(container_fs_usage_bytes)" }
     ]
    },
    {
     "title": "Usage memory",
     "type": "table-old",
     "gridPos": { "h": 12, "w": 7, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{name=~\".+\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Running Containers",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 9, "x": 7, "y": 15 },
     "targets": [
      {
       "expr": "scalar(count(container_memory_usage_bytes{image!=\"\"}) > 0)",
       "legendFormat": "container"
      }
     ]
    },
    {
     "title": "I/O Usage",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_disk_read_bytes_total[5m]))",
       "legendFormat": "read"
      },
      {
       "expr": "sum(irate(node_disk_written_bytes_total[5m]))",
       "legendFormat": "written"
      },
      {
       "expr": "sum(irate(node_disk_io_time_seconds_total[5m]))",
       "legendFormat": "io time"
      }
     ]
    },
    {
     "title": "Container CPU Usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (rate(container_cpu_user_seconds_total{container_label_org_label_schema_group=\"monitoring\"}[1m]) * 100  / scalar(count(node_cpu_seconds_total{mode=\"user\"})))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Memory Usage per Container",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_rss{name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DB (waiting for connection:D)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgreSQL Version",
     "type": "stat",
     "description": "Source: server_version_num",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(pg_settings_server_version_num)"
      }
     ]
    },
    {
     "title": "Average query runtime",
     "type": "stat",
     "description": "Source: pg_stat_statements.total_time / pg_stat_statements.calls",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((delta(pg_stat_statements_total_time_seconds{instance=\"$Instance\"}[$Interval])))/sum((delta(pg_stat_statements_calls{instance=\"$Instance\"}[$Interval])))"
      }
     ]
    },
    {
     "title": "PostgreSQL Uptime",
     "type": "stat",
     "description": "Source: pg_postmaster_start_time()",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time()-(pg_postmaster_start_time_seconds{instance=\"$Instance\"})"
      }
     ]
    },
    {
     "title": "Shared Buffer Hits",
     "type": "gauge",
     "description": "Shared buffer hits vs reads from disc",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_database_blks_hit{instance=~\"$Instance\"})/(sum(pg_stat_database_blks_hit{instance=~\"$Instance\"})+sum(pg_stat_database_blks_read{instance=~\"$Instance\"}))*100"
      }
     ]
    },
    {
     "title": "Connections used",
     "type": "gauge",
     "description": "Percentage of max_connections used",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_database_numbackends)/max(pg_settings_max_connections)"
      }
     ]
    },
    {
     "title": "Commit Ratio",
     "type": "gauge",
     "description": "Transaction committed vs rollbacked",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_database_xact_commit{instance=\"$Instance\"})/(sum(pg_stat_database_xact_commit{instance=\"$Instance\"}) + sum(pg_stat_database_xact_rollback{instance=\"$Instance\"}))"
      }
     ]
    },
    {
     "title": "Connections by state (stacked)",
     "type": "graph",
     "description": "View: pg_stat_activity",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (state) (pg_stat_activity_count{instance=\"$Instance\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Connections by database (stacked)",
     "type": "graph",
     "description": "View: pg_stat_activity",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (datname) (pg_stat_activity_count{instance=\"$Instance\"})",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Tuples inserts/updates/deletes",
     "type": "graph",
     "description": "Source: pg_stat_database",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum((rate(pg_stat_database_tup_inserted{instance=\"$Instance\"}[$Interval])))",
       "legendFormat": "Inserts"
      },
      {
       "expr": "sum((rate(pg_stat_database_tup_updated{instance=\"$Instance\"}[$Interval])))",
       "legendFormat": "Updates"
      },
      {
       "expr": "sum((rate(pg_stat_database_tup_deleted{instance=\"$Instance\"}[$Interval])))",
       "legendFormat": "Deletes"
      }
     ]
    },
    {
     "title": "Deadlocks by database",
     "type": "graph",
     "description": "Should be 0 \n\nSource: pg_stat_database\n\nWith log_lock_waits turned on, deadlocks will be logged to the PostgreSQL Logfiles.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_deadlocks{instance=\"$Instance\",datname=\"$Database\"}[$Interval])",
       "legendFormat": "deadlocks"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis (waiting for connection:D)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (redis_memory_used_bytes{instance=~\"$instance\"}  / redis_memory_max_bytes{instance=~\"$instance\"} )"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 4, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(max_over_time(redis_uptime_in_seconds{instance=~\"$instance\"}[$__interval]))"
      }
     ]
    },
    {
     "title": "Hits / Misses per Sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(redis_keyspace_hits_total{instance=~\"$instance\"}[5m])",
       "legendFormat": "hits"
      },
      {
       "expr": "irate(redis_keyspace_misses_total{instance=~\"$instance\"}[5m])",
       "legendFormat": "misses"
      }
     ]
    },
    {
     "title": "Commands Executed / sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(redis_commands_processed_total{instance=~\"$instance\"}[1m])"
      }
     ]
    },
    {
     "title": "Total Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "redis_memory_used_bytes{instance=~\"$instance\"} ",
       "legendFormat": "used"
      },
      {
       "expr": "redis_memory_max_bytes{instance=~\"$instance\"} ",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Command Calls / sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, irate(redis_commands_total{instance=~\"$instance\"} [1m]))",
       "legendFormat": "{{ cmd }}"
      }
     ]
    },
    {
     "title": "Total Items per DB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum (redis_db_keys{instance=~\"$instance\"}) by (db)",
       "legendFormat": "{{ db }} "
      }
     ]
    }
   ]
  }
 ]
}